#!/usr/bin/env python3
"""Собирает словарь: оглавление и страницы терминов из content/glossary/<lang>/*.md.
См. docs/TZ-glossary-E.md. Только stdlib (INV-03). Запускается после build_i18n.py.

Страница термина на языке собирается, только если есть MD на этом языке;
оглавление — если есть _index.md и хотя бы один термин."""
import html as html_lib
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_i18n import (  # noqa: E402
    ROOT, SRC_DIR, LANGS, SITE_URL, SITEMAP, COMMON_I18N, StopCondition,
    expand_includes, substitute_text, rewrite_links, load_pages_config,
    output_path, classify_and_rewrite, inject_lang_switch_script, strip_arrow, lastmod_for,
)

CONTENT_DIR = ROOT / "content" / "glossary"
TERMS_JSON = CONTENT_DIR / "terms.json"
LLMS_TXT = ROOT / "llms.txt"
GENERATED_PREFIX = "<!-- GENERATED by tools/build_glossary.py"

# Таблица 2.2 ТЗ: страницы сайта, на которые можно ссылаться из MD
SITE_PAGES = {"audit", "spec", "services", "metodichka", "kalkulator", "products", "portfolio", "articles", "index"}
ANSS_PATH = "/articles/anss-specification-standard-for-ai-agents.html"
LLMS_SECTION = "## Словарь"
LLMS_INSERT_BEFORE = "## Контакты"


class BuildError(Exception):
    pass


# ---------- адреса ----------

def hub_path(lang: str) -> str:
    return "/glossary/" if lang == "en" else f"/{lang}/glossary/"


def term_path(slug: str, lang: str) -> str:
    return hub_path(lang) + f"{slug}.html"


def home_path(lang: str) -> str:
    return "/" if lang == "en" else f"/{lang}/"


def out_file(path: str) -> Path:
    rel = path.lstrip("/")
    return ROOT / (rel + "index.html" if rel.endswith("/") or not rel else rel)


# ---------- чтение MD ----------

FM_LINE_RE = re.compile(r'^([a-z_]+):\s*(.*)$')


def parse_md_file(path: Path) -> tuple:
    """-> (служебный блок dict, строки тела, номер первой строки тела)."""
    lines = path.read_text(encoding="utf-8").split("\n")
    rel = path.relative_to(ROOT).as_posix()
    if not lines or lines[0].strip() != "---":
        raise BuildError(f"{rel}:1: нет служебного блока (первая строка должна быть ---)")
    meta = {}
    for i in range(1, len(lines)):
        line = lines[i]
        if line.strip() == "---":
            return meta, lines[i + 1:], i + 2
        if not line.strip():
            continue
        m = FM_LINE_RE.match(line)
        if not m:
            raise BuildError(f"{rel}:{i + 1}: строка служебного блока не в формате key: value")
        value = m.group(2).strip()
        if len(value) >= 2 and value[0] == value[-1] == '"':
            value = value[1:-1]
        meta[m.group(1)] = value
    raise BuildError(f"{rel}: служебный блок не закрыт строкой ---")


# ---------- конвертер MD (раздел 2.1) ----------

LINK_RE = re.compile(r'\[([^\]\[]+)\]\(([^()\s]+)\)')
STRONG_RE = re.compile(r'\*\*(.+?)\*\*')
FORBIDDEN_LINE_RE = re.compile(r'^(#{3,}\s|#[^# ]|>|\d+[.)]\s|\||```|~~~|[*+]\s|\s{2,}\S|\t)')
RELATED_RE = re.compile(r'^\*\*[^*]+:\*\*\s+(.+)$')


class Ctx:
    """Состояние сборки одного языка: что опубликовано, куда писать предупреждения."""

    def __init__(self, lang, published, known_slugs, migrated, warnings):
        self.lang = lang
        self.published = published
        self.known_slugs = known_slugs
        self.migrated = migrated
        self.warnings = warnings


def rewrite_md_url(url: str, ctx: Ctx, where: str):
    """-> адрес для HTML или None (ссылка снимается). Ошибка сборки, если адреса нет в таблице 2.2."""
    if url.startswith("https://"):
        return url
    path, sep, anchor = url.partition("#")
    anchor = sep + anchor
    m = re.fullmatch(r'slownik/([a-z0-9-]+)\.html', path)
    if m:
        slug = m.group(1)
        if slug not in ctx.known_slugs:
            raise BuildError(f"{where}: ссылка на термин {url}, которого нет в terms.json")
        if slug not in ctx.published:
            return None
        return term_path(slug, ctx.lang) + anchor
    if path == "anss.html":
        return ANSS_PATH + anchor
    m = re.fullmatch(r'([a-z]+)\.html', path)
    if m and m.group(1) in SITE_PAGES:
        page = m.group(1)
        if page not in ctx.migrated or not output_path(page, ctx.lang).exists():
            raise BuildError(f"{where}: ссылка {url}, а страницы {page} на языке {ctx.lang} нет")
        return classify_and_rewrite(f"{page}.html", ctx.lang, ctx.migrated) + anchor
    raise BuildError(f"{where}: ссылка {url} не из таблицы 2.2 ТЗ")


def check_text(text: str, where: str) -> None:
    for bad, name in (("`", "код"), ("<", "HTML"), ("![", "картинка"), ("[", "скобка или ссылка неверного вида"),
                      ("]", "скобка или ссылка неверного вида")):
        if bad in text:
            raise BuildError(f"{where}: разметка вне раздела 2.1 ({name}): «{text.strip()[:60]}»")
    if re.search(r'(?<![\w/])_[^_\s][^_]*_(?!\w)', text):
        raise BuildError(f"{where}: разметка вне раздела 2.1 (курсив _…_): «{text.strip()[:60]}»")


def render_inline(text: str, ctx: Ctx, where: str) -> tuple:
    """MD-строка -> (HTML, число оставшихся ссылок). Снятая ссылка остаётся текстом."""
    links = []

    def stash(m):
        links.append((m.group(1), m.group(2)))
        return f"\x00{len(links) - 1}\x00"

    work = LINK_RE.sub(stash, text)
    check_text(work, where)

    def fmt(s: str) -> str:
        s = html_lib.escape(s, quote=False)
        s = STRONG_RE.sub(r"<strong>\1</strong>", s)
        if "*" in s:
            raise BuildError(f"{where}: разметка вне раздела 2.1 (одиночная *): «{text.strip()[:60]}»")
        return s

    out = fmt(work)
    kept = 0
    for i, (label, url) in enumerate(links):
        check_text(label, where)
        label_html = fmt(label)
        href = rewrite_md_url(url, ctx, where)
        if href is None:
            ctx.warnings.append(f"{where}: «{label}» -> {url}: термин не опубликован, ссылка снята")
            repl = label_html
        else:
            kept += 1
            repl = f'<a href="{html_lib.escape(href)}">{label_html}</a>'
        out = out.replace(f"\x00{i}\x00", repl, 1)
    return out, kept


def parse_blocks(lines: list, first_line: int, rel: str) -> list:
    """Строки тела -> блоки (type, payload, номер строки)."""
    blocks = []
    para, para_line = [], 0
    items = []

    def flush():
        nonlocal para, items
        if para:
            blocks.append(("p", "\n".join(para), para_line))
            para = []
        if items:
            blocks.append(("ul", items, items[0][1]))
            items = []

    for idx, raw in enumerate(lines):
        n = first_line + idx
        line = raw.rstrip()
        where = f"{rel}:{n}"
        if not line.strip():
            flush()
            continue
        if line == "---":
            flush()
            blocks.append(("hr", None, n))
        elif line.startswith("# "):
            flush()
            blocks.append(("h1", line[2:].strip(), n))
        elif line.startswith("## "):
            flush()
            blocks.append(("h2", line[3:].strip(), n))
        elif line.startswith("- "):
            if para:
                raise BuildError(f"{where}: список без пустой строки после абзаца")
            items.append((line[2:].strip(), n))
        elif FORBIDDEN_LINE_RE.match(line):
            raise BuildError(f"{where}: разметка вне раздела 2.1: «{line[:60]}»")
        else:
            if items:
                raise BuildError(f"{where}: строка продолжения пункта списка не поддерживается")
            if not para:
                para_line = n
            para.append(line.strip())
    flush()
    return blocks


def plain(html_text: str) -> str:
    return re.sub(r"\s+", " ", html_lib.unescape(re.sub(r"<[^>]+>", "", html_text))).strip()


def render_term(path: Path, ctx: Ctx) -> dict:
    rel = path.relative_to(ROOT).as_posix()
    meta, lines, first = parse_md_file(path)
    for key in ("slug", "title", "description"):
        if not meta.get(key):
            raise BuildError(f"{rel}: в служебном блоке нет {key}")
    if meta["slug"] != path.stem:
        raise BuildError(f"{rel}: slug «{meta['slug']}» не совпадает с именем файла")
    blocks = parse_blocks(lines, first, rel)
    h1s = [b for b in blocks if b[0] == "h1"]
    if len(h1s) != 1:
        raise BuildError(f"{rel}: H1 должен быть ровно один, найдено {len(h1s)}")
    if blocks[0][0] != "h1":
        raise BuildError(f"{rel}:{blocks[0][2]}: текст до H1")
    if len(blocks) < 2 or blocks[1][0] != "p":
        raise BuildError(f"{rel}: после H1 нет абзаца-определения")

    h1_html, _ = render_inline(blocks[0][1], ctx, f"{rel}:{blocks[0][2]}")
    parts = []
    definition_html = None
    for kind, payload, n in blocks[1:]:
        where = f"{rel}:{n}"
        if kind == "h2":
            parts.append(f"<h2>{render_inline(payload, ctx, where)[0]}</h2>")
        elif kind == "hr":
            parts.append("<hr>")
        elif kind == "ul":
            lis = "".join(f"<li>{render_inline(t, ctx, f'{rel}:{ln}')[0]}</li>\n" for t, ln in payload)
            parts.append(f"<ul>\n{lis}</ul>")
        elif kind == "p":
            related = RELATED_RE.match(payload)
            html_p, kept = render_inline(payload, ctx, where)
            if related and kept == 0:
                ctx.warnings.append(f"{where}: в строке связанных терминов не осталось ссылок, строка не выводится")
                continue
            if definition_html is None:
                definition_html = html_p
            parts.append(f"<p>{html_p}</p>")
    return {
        "slug": meta["slug"], "title": meta["title"], "description": meta["description"],
        "h1": h1_html, "name": plain(h1_html), "definition": plain(definition_html),
        "body": "\n".join(parts),
    }


def render_index(path: Path, ctx: Ctx, groups: list) -> dict:
    rel = path.relative_to(ROOT).as_posix()
    meta, lines, first = parse_md_file(path)
    required = ["title", "description", "more_label", "back_label"] + [f"group_{g}" for g in groups]
    missing = [k for k in required if not meta.get(k)]
    if missing:
        raise BuildError(f"{rel}: в служебном блоке нет {missing}")
    blocks = parse_blocks(lines, first, rel)
    if [b[0] for b in blocks] != ["h1", "p"]:
        raise BuildError(f"{rel}: тело _index.md — только H1 и вступительный абзац")
    h1_html, _ = render_inline(blocks[0][1], ctx, f"{rel}:{blocks[0][2]}")
    intro_html, _ = render_inline(blocks[1][1], ctx, f"{rel}:{blocks[1][2]}")
    return {"meta": meta, "h1": h1_html, "name": plain(h1_html), "intro": intro_html}


# ---------- сборка страниц ----------

PLACEHOLDER_RE = re.compile(r"\{\{([a-z0-9_]+)\}\}")
LANG_LINK_RE = re.compile(r'<a class="([^"]*)" data-lang="(en|pl|ru)">')


def fill(template: str, values: dict, name: str) -> str:
    def sub(m):
        if m.group(1) not in values:
            raise BuildError(f"{name}: нет значения для {{{{{m.group(1)}}}}}")
        return values[m.group(1)]
    return PLACEHOLDER_RE.sub(sub, template)


def jsonld_script(data: dict) -> str:
    text = json.dumps(data, ensure_ascii=False, indent=2).replace("</", "<\\/")
    return f'<script type="application/ld+json">\n{text}\n</script>\n'


def hreflang_block(paths_by_lang: dict) -> str:
    out = "".join(f'<link rel="alternate" hreflang="{hl}" href="{SITE_URL}{p}">\n' for hl, p in paths_by_lang.items())
    if "en" in paths_by_lang:
        out += f'<link rel="alternate" hreflang="x-default" href="{SITE_URL}{paths_by_lang["en"]}">\n'
    return out


def lang_switch(page_html: str, lang: str, targets: dict) -> str:
    def sub(m):
        cls, target = m.group(1), m.group(2)
        if target == lang and "active" not in cls.split():
            cls = f"{cls} active"
        return f'<a class="{cls}" data-lang="{target}" href="{targets[target]}">'
    return LANG_LINK_RE.sub(sub, page_html)


def prepare_shell(template_name: str, lang: str, common: dict) -> str:
    """Шаблон -> общие части и тексты шапки/подвала на языке. Ссылки переписывает finish_page."""
    src = (SRC_DIR / template_name).read_text(encoding="utf-8")
    src = expand_includes(src, template_name)
    src = substitute_text(src, common[lang], lang)
    src = re.sub(r'(<meta property="og:locale" content=")[^"]*(")',
                 lambda m: m.group(1) + {"en": "en_US", "pl": "pl_PL", "ru": "ru_RU"}[lang] + m.group(2), src, count=1)
    return src


def finish_page(page: str, lang: str, migrated: set, targets: dict) -> str:
    """После подстановки значений: ссылки шапки/подвала на языковые версии, переключатель языков."""
    page = rewrite_links(page, lang, migrated)
    return lang_switch(inject_lang_switch_script(page), lang, targets)


def build() -> int:
    terms_cfg = json.loads(TERMS_JSON.read_text(encoding="utf-8"))
    groups = terms_cfg["groups"]
    order = [t["slug"] for t in terms_cfg["terms"]]
    group_of = {t["slug"]: t["group"] for t in terms_cfg["terms"]}
    bad_groups = sorted({g for g in group_of.values() if g not in groups})
    if bad_groups:
        raise BuildError(f"terms.json: группы {bad_groups} нет в списке groups")
    known = set(order)
    migrated = set(load_pages_config())
    common = json.loads(COMMON_I18N.read_text(encoding="utf-8"))

    # что есть на каждом языке
    available = {}
    has_index = {}
    for lang in LANGS:
        d = CONTENT_DIR / lang
        slugs = {p.stem for p in d.glob("*.md") if p.name != "_index.md"} if d.exists() else set()
        unknown = sorted(slugs - known)
        if unknown:
            raise BuildError(f"content/glossary/{lang}: файлы {unknown} не описаны в terms.json")
        available[lang] = slugs
        has_index[lang] = (d / "_index.md").exists()
    hub_langs = [l for l in LANGS if has_index[l] and available[l]]

    warnings = []
    written = []
    sitemap_entries = []
    llms_lines = []
    for lang in LANGS:
        if not available[lang]:
            continue
        if not has_index[lang]:
            raise BuildError(f"content/glossary/{lang}: есть статьи, но нет _index.md (нечем подписать «← Словарь»)")
        ctx = Ctx(lang, available[lang], known, migrated, warnings)
        index = render_index(CONTENT_DIR / lang / "_index.md", ctx, groups)
        meta = index["meta"]
        terms = {s: render_term(CONTENT_DIR / lang / f"{s}.md", ctx) for s in order if s in available[lang]}
        hub_url = SITE_URL + hub_path(lang)

        # страницы терминов
        term_tpl = prepare_shell("glossary-term.template.html", lang, common)
        for slug, t in terms.items():
            url = SITE_URL + term_path(slug, lang)
            versions = {l: term_path(slug, l) for l in LANGS if slug in available[l]}
            targets = {l: term_path(slug, l) if slug in available[l] else hub_path(l) if l in hub_langs else home_path(l)
                       for l in LANGS}
            ld = jsonld_script({
                "@context": "https://schema.org", "@type": "DefinedTerm",
                "name": t["name"], "description": t["definition"], "url": url, "inLanguage": lang,
                "inDefinedTermSet": hub_url,
            }) + jsonld_script({
                "@context": "https://schema.org", "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": strip_arrow(common[lang]["nav_home"]), "item": SITE_URL + home_path(lang)},
                    {"@type": "ListItem", "position": 2, "name": index["name"], "item": hub_url},
                    {"@type": "ListItem", "position": 3, "name": t["name"], "item": url},
                ],
            })
            page = fill(term_tpl, {
                "lang": lang, "title": html_lib.escape(t["title"]), "description": html_lib.escape(t["description"]),
                "url": url, "hreflang": hreflang_block(versions), "jsonld": ld,
                "hub_url": hub_path(lang), "back_label": html_lib.escape(meta["back_label"]),
                "h1": t["h1"], "body": t["body"],
            }, f"{lang}/{slug}")
            page = finish_page(page, lang, migrated, targets)
            banner = f"{GENERATED_PREFIX} from content/glossary/{lang}/{slug}.md; do not edit -->\n"
            written.append((term_path(slug, lang), banner + page))
            sitemap_entries.append((term_path(slug, lang), "0.6"))
            first_sentence = re.match(r"^(.+?[.!?])(?:\s|$)", t["definition"])
            llms_lines.append(f"- [{t['name']}]({url}): {first_sentence.group(1) if first_sentence else t['definition']}")

        # оглавление
        cards_by_group = {g: [] for g in groups}
        for slug, t in terms.items():
            cards_by_group[group_of[slug]].append(
                ' <div class="article-card">\n'
                f' <h3>{t["h1"]}</h3>\n'
                f' <p>{html_lib.escape(t["definition"], quote=False)}</p>\n'
                f' <a class="article-cta" href="{term_path(slug, lang)}">{html_lib.escape(meta["more_label"])}</a>\n'
                ' </div>\n'
            )
        sections = "".join(
            f' <section>\n <h2>{html_lib.escape(meta["group_" + g])}</h2>\n <div class="article-grid">\n'
            + "".join(cards) + ' </div>\n </section>\n\n'
            for g, cards in cards_by_group.items() if cards
        )
        ld = jsonld_script({
            "@context": "https://schema.org", "@type": "DefinedTermSet",
            "name": index["name"], "description": plain(index["intro"]), "url": hub_url, "inLanguage": lang,
            "hasDefinedTerm": [
                {"@type": "DefinedTerm", "name": t["name"], "description": t["definition"],
                 "url": SITE_URL + term_path(s, lang)}
                for s, t in terms.items()
            ],
        })
        hub_tpl = prepare_shell("glossary-hub.template.html", lang, common)
        page = fill(hub_tpl, {
            "lang": lang, "title": html_lib.escape(meta["title"]), "description": html_lib.escape(meta["description"]),
            "url": hub_url, "hreflang": hreflang_block({l: hub_path(l) for l in hub_langs}), "jsonld": ld,
            "h1": index["h1"], "intro": index["intro"], "groups": sections,
        }, f"{lang}/_index")
        page = finish_page(page, lang, migrated, {l: hub_path(l) if l in hub_langs else home_path(l) for l in LANGS})
        banner = f"{GENERATED_PREFIX} from content/glossary/{lang}/_index.md; do not edit -->\n"
        written.insert(len(written) - len(terms), (hub_path(lang), banner + page))
        sitemap_entries.insert(len(sitemap_entries) - len(terms), (hub_path(lang), "0.7"))

    # запись, удаление устаревших сгенерированных страниц
    targets = {out_file(p) for p, _ in written}
    for lang in LANGS:
        d = out_file(hub_path(lang)).parent
        if not d.exists():
            continue
        for f in d.glob("*.html"):
            if f not in targets and f.read_text(encoding="utf-8").startswith(GENERATED_PREFIX):
                f.unlink()
                print(f"  удалён устаревший {f.relative_to(ROOT).as_posix()}")
        if not any(d.iterdir()):
            d.rmdir()
    for p, text in written:
        f = out_file(p)
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(text, encoding="utf-8")
        print(f"  {f.relative_to(ROOT).as_posix()}")

    update_sitemap(sitemap_entries)
    update_llms(llms_lines)

    print(f"Словарь: {len(written)} страниц. Предупреждений: {len(warnings)}")
    for w in warnings:
        print(f"ПРЕДУПРЕЖДЕНИЕ: {w}")
    return 0


# ---------- sitemap.xml и llms.txt ----------

def update_sitemap(entries: list) -> None:
    """Блоки /glossary/ убираются и добавляются заново в конец, в формате build_i18n.rebuild_sitemap."""
    src = SITEMAP.read_text(encoding="utf-8")
    m = re.match(r"(.*?<urlset[^>]*>\n)((?: <url>.*?</url>\n)*)(</urlset>\n?)", src, re.DOTALL)
    if not m:
        raise BuildError("sitemap.xml: формат не распознан")
    header, body, footer = m.groups()
    kept = [f" <url>\n{c}\n </url>\n" for c in re.findall(r" <url>\n(.*?)\n </url>\n", body, re.DOTALL)
            if "/glossary/" not in re.search(r"<loc>([^<]+)</loc>", c).group(1)]
    new = [
        " <url>\n"
        f" <loc>{SITE_URL}{p}</loc>\n"
        f" <lastmod>{lastmod_for(out_file(p))}</lastmod>\n"
        " <changefreq>monthly</changefreq>\n"
        f" <priority>{prio}</priority>\n"
        " </url>\n"
        for p, prio in entries
    ]
    SITEMAP.write_text(header + "".join(kept + new) + footer, encoding="utf-8")


def update_llms(lines: list) -> None:
    """Раздел «## Словарь» пересобирается, остальной файл не трогается. Нет терминов — раздела нет."""
    src = LLMS_TXT.read_text(encoding="utf-8")
    section = (LLMS_SECTION + "\n\n" + "\n".join(lines) + "\n\n") if lines else ""
    m = re.search(rf"^{re.escape(LLMS_SECTION)}\n.*?(?=^## |\Z)", src, re.DOTALL | re.MULTILINE)
    if m:
        out = src[:m.start()] + section + src[m.end():]
    else:
        pos = src.find(LLMS_INSERT_BEFORE)
        if pos == -1:
            raise BuildError(f"llms.txt: нет раздела «{LLMS_INSERT_BEFORE}», некуда вставить словарь")
        out = src[:pos] + section + src[pos:]
    if out != src:
        LLMS_TXT.write_text(out, encoding="utf-8")


def main():
    try:
        return build()
    except (BuildError, StopCondition) as e:
        print(f"ОШИБКА СБОРКИ СЛОВАРЯ: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
